// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/currency_converter.proto

package currencyconverterpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CurrencyConverter_GetExchangeRate_FullMethodName        = "/currency.converter.CurrencyConverter/GetExchangeRate"
	CurrencyConverter_ConvertAmount_FullMethodName          = "/currency.converter.CurrencyConverter/ConvertAmount"
	CurrencyConverter_GetSupportedCurrencies_FullMethodName = "/currency.converter.CurrencyConverter/GetSupportedCurrencies"
)

// CurrencyConverterClient is the client API for CurrencyConverter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CurrencyConverterClient interface {
	GetExchangeRate(ctx context.Context, in *GetExchangeRateRequest, opts ...grpc.CallOption) (*GetExchangeRateResponse, error)
	ConvertAmount(ctx context.Context, in *ConvertAmountRequest, opts ...grpc.CallOption) (*ConvertAmountResponse, error)
	GetSupportedCurrencies(ctx context.Context, in *GetSupportedCurrenciesRequest, opts ...grpc.CallOption) (*GetSupportedCurrenciesResponse, error)
}

type currencyConverterClient struct {
	cc grpc.ClientConnInterface
}

func NewCurrencyConverterClient(cc grpc.ClientConnInterface) CurrencyConverterClient {
	return &currencyConverterClient{cc}
}

func (c *currencyConverterClient) GetExchangeRate(ctx context.Context, in *GetExchangeRateRequest, opts ...grpc.CallOption) (*GetExchangeRateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetExchangeRateResponse)
	err := c.cc.Invoke(ctx, CurrencyConverter_GetExchangeRate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *currencyConverterClient) ConvertAmount(ctx context.Context, in *ConvertAmountRequest, opts ...grpc.CallOption) (*ConvertAmountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConvertAmountResponse)
	err := c.cc.Invoke(ctx, CurrencyConverter_ConvertAmount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *currencyConverterClient) GetSupportedCurrencies(ctx context.Context, in *GetSupportedCurrenciesRequest, opts ...grpc.CallOption) (*GetSupportedCurrenciesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSupportedCurrenciesResponse)
	err := c.cc.Invoke(ctx, CurrencyConverter_GetSupportedCurrencies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CurrencyConverterServer is the server API for CurrencyConverter service.
// All implementations must embed UnimplementedCurrencyConverterServer
// for forward compatibility.
type CurrencyConverterServer interface {
	GetExchangeRate(context.Context, *GetExchangeRateRequest) (*GetExchangeRateResponse, error)
	ConvertAmount(context.Context, *ConvertAmountRequest) (*ConvertAmountResponse, error)
	GetSupportedCurrencies(context.Context, *GetSupportedCurrenciesRequest) (*GetSupportedCurrenciesResponse, error)
	mustEmbedUnimplementedCurrencyConverterServer()
}

// UnimplementedCurrencyConverterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCurrencyConverterServer struct{}

func (UnimplementedCurrencyConverterServer) GetExchangeRate(context.Context, *GetExchangeRateRequest) (*GetExchangeRateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetExchangeRate not implemented")
}
func (UnimplementedCurrencyConverterServer) ConvertAmount(context.Context, *ConvertAmountRequest) (*ConvertAmountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConvertAmount not implemented")
}
func (UnimplementedCurrencyConverterServer) GetSupportedCurrencies(context.Context, *GetSupportedCurrenciesRequest) (*GetSupportedCurrenciesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSupportedCurrencies not implemented")
}
func (UnimplementedCurrencyConverterServer) mustEmbedUnimplementedCurrencyConverterServer() {}
func (UnimplementedCurrencyConverterServer) testEmbeddedByValue()                           {}

// UnsafeCurrencyConverterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CurrencyConverterServer will
// result in compilation errors.
type UnsafeCurrencyConverterServer interface {
	mustEmbedUnimplementedCurrencyConverterServer()
}

func RegisterCurrencyConverterServer(s grpc.ServiceRegistrar, srv CurrencyConverterServer) {
	// If the following call panics, it indicates UnimplementedCurrencyConverterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CurrencyConverter_ServiceDesc, srv)
}

func _CurrencyConverter_GetExchangeRate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExchangeRateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CurrencyConverterServer).GetExchangeRate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CurrencyConverter_GetExchangeRate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CurrencyConverterServer).GetExchangeRate(ctx, req.(*GetExchangeRateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CurrencyConverter_ConvertAmount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConvertAmountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CurrencyConverterServer).ConvertAmount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CurrencyConverter_ConvertAmount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CurrencyConverterServer).ConvertAmount(ctx, req.(*ConvertAmountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CurrencyConverter_GetSupportedCurrencies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSupportedCurrenciesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CurrencyConverterServer).GetSupportedCurrencies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CurrencyConverter_GetSupportedCurrencies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CurrencyConverterServer).GetSupportedCurrencies(ctx, req.(*GetSupportedCurrenciesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CurrencyConverter_ServiceDesc is the grpc.ServiceDesc for CurrencyConverter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CurrencyConverter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "currency.converter.CurrencyConverter",
	HandlerType: (*CurrencyConverterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetExchangeRate",
			Handler:    _CurrencyConverter_GetExchangeRate_Handler,
		},
		{
			MethodName: "ConvertAmount",
			Handler:    _CurrencyConverter_ConvertAmount_Handler,
		},
		{
			MethodName: "GetSupportedCurrencies",
			Handler:    _CurrencyConverter_GetSupportedCurrencies_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/currency_converter.proto",
}
