// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/currency_converter.proto

package currencyconverterpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetExchangeRateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromCurrency  string                 `protobuf:"bytes,1,opt,name=from_currency,json=fromCurrency,proto3" json:"from_currency,omitempty"`
	ToCurrency    string                 `protobuf:"bytes,2,opt,name=to_currency,json=toCurrency,proto3" json:"to_currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExchangeRateRequest) Reset() {
	*x = GetExchangeRateRequest{}
	mi := &file_proto_currency_converter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExchangeRateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExchangeRateRequest) ProtoMessage() {}

func (x *GetExchangeRateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_currency_converter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExchangeRateRequest.ProtoReflect.Descriptor instead.
func (*GetExchangeRateRequest) Descriptor() ([]byte, []int) {
	return file_proto_currency_converter_proto_rawDescGZIP(), []int{0}
}

func (x *GetExchangeRateRequest) GetFromCurrency() string {
	if x != nil {
		return x.FromCurrency
	}
	return ""
}

func (x *GetExchangeRateRequest) GetToCurrency() string {
	if x != nil {
		return x.ToCurrency
	}
	return ""
}

type GetExchangeRateResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Rate           float64                `protobuf:"fixed64,1,opt,name=rate,proto3" json:"rate,omitempty"`
	Source         string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	BaseCurrency   string                 `protobuf:"bytes,3,opt,name=base_currency,json=baseCurrency,proto3" json:"base_currency,omitempty"`
	TargetCurrency string                 `protobuf:"bytes,4,opt,name=target_currency,json=targetCurrency,proto3" json:"target_currency,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetExchangeRateResponse) Reset() {
	*x = GetExchangeRateResponse{}
	mi := &file_proto_currency_converter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExchangeRateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExchangeRateResponse) ProtoMessage() {}

func (x *GetExchangeRateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_currency_converter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExchangeRateResponse.ProtoReflect.Descriptor instead.
func (*GetExchangeRateResponse) Descriptor() ([]byte, []int) {
	return file_proto_currency_converter_proto_rawDescGZIP(), []int{1}
}

func (x *GetExchangeRateResponse) GetRate() float64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *GetExchangeRateResponse) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *GetExchangeRateResponse) GetBaseCurrency() string {
	if x != nil {
		return x.BaseCurrency
	}
	return ""
}

func (x *GetExchangeRateResponse) GetTargetCurrency() string {
	if x != nil {
		return x.TargetCurrency
	}
	return ""
}

type ConvertAmountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        float64                `protobuf:"fixed64,1,opt,name=amount,proto3" json:"amount,omitempty"`
	FromCurrency  string                 `protobuf:"bytes,2,opt,name=from_currency,json=fromCurrency,proto3" json:"from_currency,omitempty"`
	ToCurrency    string                 `protobuf:"bytes,3,opt,name=to_currency,json=toCurrency,proto3" json:"to_currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConvertAmountRequest) Reset() {
	*x = ConvertAmountRequest{}
	mi := &file_proto_currency_converter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertAmountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertAmountRequest) ProtoMessage() {}

func (x *ConvertAmountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_currency_converter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertAmountRequest.ProtoReflect.Descriptor instead.
func (*ConvertAmountRequest) Descriptor() ([]byte, []int) {
	return file_proto_currency_converter_proto_rawDescGZIP(), []int{2}
}

func (x *ConvertAmountRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ConvertAmountRequest) GetFromCurrency() string {
	if x != nil {
		return x.FromCurrency
	}
	return ""
}

func (x *ConvertAmountRequest) GetToCurrency() string {
	if x != nil {
		return x.ToCurrency
	}
	return ""
}

type ConvertAmountResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ConvertedAmount float64                `protobuf:"fixed64,1,opt,name=converted_amount,json=convertedAmount,proto3" json:"converted_amount,omitempty"`
	Rate            float64                `protobuf:"fixed64,2,opt,name=rate,proto3" json:"rate,omitempty"`
	Source          string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	BaseCurrency    string                 `protobuf:"bytes,4,opt,name=base_currency,json=baseCurrency,proto3" json:"base_currency,omitempty"`
	TargetCurrency  string                 `protobuf:"bytes,5,opt,name=target_currency,json=targetCurrency,proto3" json:"target_currency,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ConvertAmountResponse) Reset() {
	*x = ConvertAmountResponse{}
	mi := &file_proto_currency_converter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertAmountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertAmountResponse) ProtoMessage() {}

func (x *ConvertAmountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_currency_converter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertAmountResponse.ProtoReflect.Descriptor instead.
func (*ConvertAmountResponse) Descriptor() ([]byte, []int) {
	return file_proto_currency_converter_proto_rawDescGZIP(), []int{3}
}

func (x *ConvertAmountResponse) GetConvertedAmount() float64 {
	if x != nil {
		return x.ConvertedAmount
	}
	return 0
}

func (x *ConvertAmountResponse) GetRate() float64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *ConvertAmountResponse) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ConvertAmountResponse) GetBaseCurrency() string {
	if x != nil {
		return x.BaseCurrency
	}
	return ""
}

func (x *ConvertAmountResponse) GetTargetCurrency() string {
	if x != nil {
		return x.TargetCurrency
	}
	return ""
}

type GetSupportedCurrenciesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSupportedCurrenciesRequest) Reset() {
	*x = GetSupportedCurrenciesRequest{}
	mi := &file_proto_currency_converter_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSupportedCurrenciesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSupportedCurrenciesRequest) ProtoMessage() {}

func (x *GetSupportedCurrenciesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_currency_converter_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSupportedCurrenciesRequest.ProtoReflect.Descriptor instead.
func (*GetSupportedCurrenciesRequest) Descriptor() ([]byte, []int) {
	return file_proto_currency_converter_proto_rawDescGZIP(), []int{4}
}

type GetSupportedCurrenciesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Currencies    []string               `protobuf:"bytes,1,rep,name=currencies,proto3" json:"currencies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSupportedCurrenciesResponse) Reset() {
	*x = GetSupportedCurrenciesResponse{}
	mi := &file_proto_currency_converter_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSupportedCurrenciesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSupportedCurrenciesResponse) ProtoMessage() {}

func (x *GetSupportedCurrenciesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_currency_converter_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSupportedCurrenciesResponse.ProtoReflect.Descriptor instead.
func (*GetSupportedCurrenciesResponse) Descriptor() ([]byte, []int) {
	return file_proto_currency_converter_proto_rawDescGZIP(), []int{5}
}

func (x *GetSupportedCurrenciesResponse) GetCurrencies() []string {
	if x != nil {
		return x.Currencies
	}
	return nil
}

var File_proto_currency_converter_proto protoreflect.FileDescriptor

const file_proto_currency_converter_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/currency_converter.proto\x12\x12currency.converter\"^\n" +
	"\x16GetExchangeRateRequest\x12#\n" +
	"\rfrom_currency\x18\x01 \x01(\tR\ffromCurrency\x12\x1f\n" +
	"\vto_currency\x18\x02 \x01(\tR\n" +
	"toCurrency\"\x93\x01\n" +
	"\x17GetExchangeRateResponse\x12\x12\n" +
	"\x04rate\x18\x01 \x01(\x01R\x04rate\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12#\n" +
	"\rbase_currency\x18\x03 \x01(\tR\fbaseCurrency\x12'\n" +
	"\x0ftarget_currency\x18\x04 \x01(\tR\x0etargetCurrency\"t\n" +
	"\x14ConvertAmountRequest\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x01R\x06amount\x12#\n" +
	"\rfrom_currency\x18\x02 \x01(\tR\ffromCurrency\x12\x1f\n" +
	"\vto_currency\x18\x03 \x01(\tR\n" +
	"toCurrency\"\xbc\x01\n" +
	"\x15ConvertAmountResponse\x12)\n" +
	"\x10converted_amount\x18\x01 \x01(\x01R\x0fconvertedAmount\x12\x12\n" +
	"\x04rate\x18\x02 \x01(\x01R\x04rate\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12#\n" +
	"\rbase_currency\x18\x04 \x01(\tR\fbaseCurrency\x12'\n" +
	"\x0ftarget_currency\x18\x05 \x01(\tR\x0etargetCurrency\"\x1f\n" +
	"\x1dGetSupportedCurrenciesRequest\"@\n" +
	"\x1eGetSupportedCurrenciesResponse\x12\x1e\n" +
	"\n" +
	"currencies\x18\x01 \x03(\tR\n" +
	"currencies2\xe6\x02\n" +
	"\x11CurrencyConverter\x12j\n" +
	"\x0fGetExchangeRate\x12*.currency.converter.GetExchangeRateRequest\x1a+.currency.converter.GetExchangeRateResponse\x12d\n" +
	"\rConvertAmount\x12(.currency.converter.ConvertAmountRequest\x1a).currency.converter.ConvertAmountResponse\x12\x7f\n" +
	"\x16GetSupportedCurrencies\x121.currency.converter.GetSupportedCurrenciesRequest\x1a2.currency.converter.GetSupportedCurrenciesResponseB6Z4currency-converter-service/proto;currencyconverterpbb\x06proto3"

var (
	file_proto_currency_converter_proto_rawDescOnce sync.Once
	file_proto_currency_converter_proto_rawDescData []byte
)

func file_proto_currency_converter_proto_rawDescGZIP() []byte {
	file_proto_currency_converter_proto_rawDescOnce.Do(func() {
		file_proto_currency_converter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_currency_converter_proto_rawDesc), len(file_proto_currency_converter_proto_rawDesc)))
	})
	return file_proto_currency_converter_proto_rawDescData
}

var file_proto_currency_converter_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_currency_converter_proto_goTypes = []any{
	(*GetExchangeRateRequest)(nil),         // 0: currency.converter.GetExchangeRateRequest
	(*GetExchangeRateResponse)(nil),        // 1: currency.converter.GetExchangeRateResponse
	(*ConvertAmountRequest)(nil),           // 2: currency.converter.ConvertAmountRequest
	(*ConvertAmountResponse)(nil),          // 3: currency.converter.ConvertAmountResponse
	(*GetSupportedCurrenciesRequest)(nil),  // 4: currency.converter.GetSupportedCurrenciesRequest
	(*GetSupportedCurrenciesResponse)(nil), // 5: currency.converter.GetSupportedCurrenciesResponse
}
var file_proto_currency_converter_proto_depIdxs = []int32{
	0, // 0: currency.converter.CurrencyConverter.GetExchangeRate:input_type -> currency.converter.GetExchangeRateRequest
	2, // 1: currency.converter.CurrencyConverter.ConvertAmount:input_type -> currency.converter.ConvertAmountRequest
	4, // 2: currency.converter.CurrencyConverter.GetSupportedCurrencies:input_type -> currency.converter.GetSupportedCurrenciesRequest
	1, // 3: currency.converter.CurrencyConverter.GetExchangeRate:output_type -> currency.converter.GetExchangeRateResponse
	3, // 4: currency.converter.CurrencyConverter.ConvertAmount:output_type -> currency.converter.ConvertAmountResponse
	5, // 5: currency.converter.CurrencyConverter.GetSupportedCurrencies:output_type -> currency.converter.GetSupportedCurrenciesResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_currency_converter_proto_init() }
func file_proto_currency_converter_proto_init() {
	if File_proto_currency_converter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_currency_converter_proto_rawDesc), len(file_proto_currency_converter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_currency_converter_proto_goTypes,
		DependencyIndexes: file_proto_currency_converter_proto_depIdxs,
		MessageInfos:      file_proto_currency_converter_proto_msgTypes,
	}.Build()
	File_proto_currency_converter_proto = out.File
	file_proto_currency_converter_proto_goTypes = nil
	file_proto_currency_converter_proto_depIdxs = nil
}
