//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingService.CurrencyConverterService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="Currencies", Namespace="http://example.com/currencyconverter", ItemName="Currency")]
    public class Currencies : System.Collections.Generic.List<string>
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://example.com/currencyconverter", ConfigurationName="BookingService.CurrencyConverterService.CurrencyConverterPortType")]
    public interface CurrencyConverterPortType
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="GetExchangeRate", ReplyAction="*")]
        System.Threading.Tasks.Task<BookingService.CurrencyConverterService.GetExchangeRateResponse> GetExchangeRateAsync(BookingService.CurrencyConverterService.GetExchangeRateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="ConvertAmount", ReplyAction="*")]
        System.Threading.Tasks.Task<BookingService.CurrencyConverterService.ConvertAmountResponse> ConvertAmountAsync(BookingService.CurrencyConverterService.ConvertAmountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="GetSupportedCurrencies", ReplyAction="*")]
        System.Threading.Tasks.Task<BookingService.CurrencyConverterService.GetSupportedCurrenciesResponse> GetSupportedCurrenciesAsync(BookingService.CurrencyConverterService.GetSupportedCurrenciesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetExchangeRateRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetExchangeRateRequest", Namespace="http://example.com/currencyconverter", Order=0)]
        public BookingService.CurrencyConverterService.GetExchangeRateRequestBody Body;
        
        public GetExchangeRateRequest()
        {
        }
        
        public GetExchangeRateRequest(BookingService.CurrencyConverterService.GetExchangeRateRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://example.com/currencyconverter")]
    public partial class GetExchangeRateRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FromCurrency;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ToCurrency;
        
        public GetExchangeRateRequestBody()
        {
        }
        
        public GetExchangeRateRequestBody(string FromCurrency, string ToCurrency)
        {
            this.FromCurrency = FromCurrency;
            this.ToCurrency = ToCurrency;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetExchangeRateResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetExchangeRateResponse", Namespace="http://example.com/currencyconverter", Order=0)]
        public BookingService.CurrencyConverterService.GetExchangeRateResponseBody Body;
        
        public GetExchangeRateResponse()
        {
        }
        
        public GetExchangeRateResponse(BookingService.CurrencyConverterService.GetExchangeRateResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://example.com/currencyconverter")]
    public partial class GetExchangeRateResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double Rate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Source;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string BaseCurrency;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string TargetCurrency;
        
        public GetExchangeRateResponseBody()
        {
        }
        
        public GetExchangeRateResponseBody(double Rate, string Source, string BaseCurrency, string TargetCurrency)
        {
            this.Rate = Rate;
            this.Source = Source;
            this.BaseCurrency = BaseCurrency;
            this.TargetCurrency = TargetCurrency;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConvertAmountRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConvertAmountRequest", Namespace="http://example.com/currencyconverter", Order=0)]
        public BookingService.CurrencyConverterService.ConvertAmountRequestBody Body;
        
        public ConvertAmountRequest()
        {
        }
        
        public ConvertAmountRequest(BookingService.CurrencyConverterService.ConvertAmountRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://example.com/currencyconverter")]
    public partial class ConvertAmountRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double Amount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string FromCurrency;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ToCurrency;
        
        public ConvertAmountRequestBody()
        {
        }
        
        public ConvertAmountRequestBody(double Amount, string FromCurrency, string ToCurrency)
        {
            this.Amount = Amount;
            this.FromCurrency = FromCurrency;
            this.ToCurrency = ToCurrency;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConvertAmountResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConvertAmountResponse", Namespace="http://example.com/currencyconverter", Order=0)]
        public BookingService.CurrencyConverterService.ConvertAmountResponseBody Body;
        
        public ConvertAmountResponse()
        {
        }
        
        public ConvertAmountResponse(BookingService.CurrencyConverterService.ConvertAmountResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://example.com/currencyconverter")]
    public partial class ConvertAmountResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double ConvertedAmount;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double Rate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Source;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string BaseCurrency;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string TargetCurrency;
        
        public ConvertAmountResponseBody()
        {
        }
        
        public ConvertAmountResponseBody(double ConvertedAmount, double Rate, string Source, string BaseCurrency, string TargetCurrency)
        {
            this.ConvertedAmount = ConvertedAmount;
            this.Rate = Rate;
            this.Source = Source;
            this.BaseCurrency = BaseCurrency;
            this.TargetCurrency = TargetCurrency;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSupportedCurrenciesRequest", WrapperNamespace="http://example.com/currencyconverter", IsWrapped=true)]
    public partial class GetSupportedCurrenciesRequest
    {
        
        public GetSupportedCurrenciesRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSupportedCurrenciesResponse", WrapperNamespace="http://example.com/currencyconverter", IsWrapped=true)]
    public partial class GetSupportedCurrenciesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://example.com/currencyconverter", Order=0)]
        public BookingService.CurrencyConverterService.Currencies Currencies;
        
        public GetSupportedCurrenciesResponse()
        {
        }
        
        public GetSupportedCurrenciesResponse(BookingService.CurrencyConverterService.Currencies Currencies)
        {
            this.Currencies = Currencies;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface CurrencyConverterPortTypeChannel : BookingService.CurrencyConverterService.CurrencyConverterPortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class CurrencyConverterPortTypeClient : System.ServiceModel.ClientBase<BookingService.CurrencyConverterService.CurrencyConverterPortType>, BookingService.CurrencyConverterService.CurrencyConverterPortType
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CurrencyConverterPortTypeClient() : 
                base(CurrencyConverterPortTypeClient.GetDefaultBinding(), CurrencyConverterPortTypeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.CurrencyConverterPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CurrencyConverterPortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(CurrencyConverterPortTypeClient.GetBindingForEndpoint(endpointConfiguration), CurrencyConverterPortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CurrencyConverterPortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CurrencyConverterPortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CurrencyConverterPortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CurrencyConverterPortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CurrencyConverterPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BookingService.CurrencyConverterService.GetExchangeRateResponse> BookingService.CurrencyConverterService.CurrencyConverterPortType.GetExchangeRateAsync(BookingService.CurrencyConverterService.GetExchangeRateRequest request)
        {
            return base.Channel.GetExchangeRateAsync(request);
        }
        
        public System.Threading.Tasks.Task<BookingService.CurrencyConverterService.GetExchangeRateResponse> GetExchangeRateAsync(string FromCurrency, string ToCurrency)
        {
            BookingService.CurrencyConverterService.GetExchangeRateRequest inValue = new BookingService.CurrencyConverterService.GetExchangeRateRequest();
            inValue.Body = new BookingService.CurrencyConverterService.GetExchangeRateRequestBody();
            inValue.Body.FromCurrency = FromCurrency;
            inValue.Body.ToCurrency = ToCurrency;
            return ((BookingService.CurrencyConverterService.CurrencyConverterPortType)(this)).GetExchangeRateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BookingService.CurrencyConverterService.ConvertAmountResponse> BookingService.CurrencyConverterService.CurrencyConverterPortType.ConvertAmountAsync(BookingService.CurrencyConverterService.ConvertAmountRequest request)
        {
            return base.Channel.ConvertAmountAsync(request);
        }
        
        public System.Threading.Tasks.Task<BookingService.CurrencyConverterService.ConvertAmountResponse> ConvertAmountAsync(double Amount, string FromCurrency, string ToCurrency)
        {
            BookingService.CurrencyConverterService.ConvertAmountRequest inValue = new BookingService.CurrencyConverterService.ConvertAmountRequest();
            inValue.Body = new BookingService.CurrencyConverterService.ConvertAmountRequestBody();
            inValue.Body.Amount = Amount;
            inValue.Body.FromCurrency = FromCurrency;
            inValue.Body.ToCurrency = ToCurrency;
            return ((BookingService.CurrencyConverterService.CurrencyConverterPortType)(this)).ConvertAmountAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BookingService.CurrencyConverterService.GetSupportedCurrenciesResponse> BookingService.CurrencyConverterService.CurrencyConverterPortType.GetSupportedCurrenciesAsync(BookingService.CurrencyConverterService.GetSupportedCurrenciesRequest request)
        {
            return base.Channel.GetSupportedCurrenciesAsync(request);
        }
        
        public System.Threading.Tasks.Task<BookingService.CurrencyConverterService.GetSupportedCurrenciesResponse> GetSupportedCurrenciesAsync()
        {
            BookingService.CurrencyConverterService.GetSupportedCurrenciesRequest inValue = new BookingService.CurrencyConverterService.GetSupportedCurrenciesRequest();
            return ((BookingService.CurrencyConverterService.CurrencyConverterPortType)(this)).GetSupportedCurrenciesAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CurrencyConverterPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CurrencyConverterPort))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8080/soap");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return CurrencyConverterPortTypeClient.GetBindingForEndpoint(EndpointConfiguration.CurrencyConverterPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return CurrencyConverterPortTypeClient.GetEndpointAddress(EndpointConfiguration.CurrencyConverterPort);
        }
        
        public enum EndpointConfiguration
        {
            
            CurrencyConverterPort,
        }
    }
}
