services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: mssql_server
    restart: unless-stopped
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourStrong!Passw0rd"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P $$MSSQL_SA_PASSWORD -C -Q 'SELECT 1' || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    networks:
      - carrental-network

  car-rental-service:
    build:
      context: ../../CarRentalService
      dockerfile: Dockerfile
    container_name: car-rental-service
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Server=mssql,1433;Database=CarRentalDB;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;"
    ports:
      - "8080:8080"
    depends_on:
      mssql:
        condition: service_healthy
    networks:
      - carrental-network

  db-seeder:
    image: mcr.microsoft.com/mssql/server:2025-latest
    depends_on:
      mssql:
        condition: service_healthy
    volumes:
      - ./seed.sql:/seed.sql:ro
      - ./seed.sh:/seed.sh:ro
    entrypoint: ["/bin/bash", "/seed.sh"]
    restart: "no"
    networks:
      - carrental-network

  currency-converter-service:
    build:
      context: ../../CurrencyConverterService
      dockerfile: Dockerfile
    container_name: currency-converter-service
    restart: unless-stopped
    ports:
      - "8081:8080"
    networks:
      - carrental-network

  keycloak:
    image: quay.io/keycloak/keycloak:26.1
    container_name: keycloak
    restart: unless-stopped
    command:
      - start-dev
      - --http-enabled=true
      - --hostname-strict=false
      - --import-realm
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: "root"
      KC_BOOTSTRAP_ADMIN_PASSWORD: "root"
    ports:
      - "8082:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ./car-rental-dev-realm.json:/opt/keycloak/data/import/car-rental-dev-realm.json:ro
      - ../keycloak-themes:/opt/keycloak/themes:ro
    networks:
      - carrental-network

volumes:
  mssql_data:
  keycloak_data:

networks:
  carrental-network:
    driver: bridge
